# Generated by Django 2.0.1 on 2018-07-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField(verbose_name='日付')),
                ('StudentID', models.CharField(max_length=255, verbose_name='生徒番号')),
                ('TeacherID', models.CharField(max_length=255, verbose_name='講師番号')),
                ('Subject', models.CharField(max_length=255, verbose_name='教科')),
                ('Subject_Unit', models.CharField(max_length=255, verbose_name='単元')),
                ('Textbook', models.CharField(max_length=255, verbose_name='テキスト')),
                ('Rating', models.CharField(max_length=255, verbose_name='評価')),
                ('Rating_Reason', models.CharField(max_length=255, verbose_name='コメント')),
                ('HomeworkID', models.CharField(max_length=255, verbose_name='宿題番号')),
            ],
        ),
    ]
